### ISSUE TITLE
Format Document should not reformat comments

### ISSUE THREAD

**Issue by JimThatcher** [Juancete/gcode-vsc-formatter#4]
When running the Format Document processing, extra spaces and zero-padding should not be applied to test inside of comments. For example, "(TEST CIRCLE)" comment is current reformatted to "( T0E S T0 C I RCLE)". It should be left as-is.

**Comment by Juancete** [comment]
Hi @JimThatcher,

  Thank you very much for taking the time to create the issue. I made the fix. The new version will be available very soon. 

Best regards,
Juan
