### ISSUE TITLE
Request to handle variables and conditional statments better

### ISSUE THREAD

**Issue by jokesters** [Juancete/gcode-vsc-formatter#6]
I use lots of conditional IF, WHILE statements and named variables.  For example my statement "IF[[#GYGZ]EQ0]GOTO999" formatted to "I F[[# G0 Y G0 Z]EQ0] G0O TO999". Maybe ignore lines that start with IF, WHILE, END, GOTO, SETVN, and anything inside "[]". Also noticed it doesn't put a space after G65 or G04, I think this could be a pretty handy extension to make the G-Code easier to read and look cleaner but I program for a repair facility that programs have to be able to handle conditions of what needs to repaired so if it can't handle these functions I cant use it.

**Comment by Juancete** [comment]
Hi @jokesters ,

I fix the conditional issue. Can you open a new issue about G65 or G04 and add an example? I'm building a new release
